version: '2'

services:
  api:
    ports:
      - 8000:8000
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    restart: always
    networks:
      - saleor-backend-tier
    depends_on:
      - db
      - redis
      - jaeger
    volumes:
      - ./saleor/saleor/:/app/saleor:Z
      - ./saleor/templates/:/app/templates:Z
      - ./saleor/tests/:/app/tests
      # shared volume between worker and api for media
      - saleor-media:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    env_file: common.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - STOREFRONT_URL=https://${HOST_NAME}/
      - MEDIA_URL=https://${HOST_NAME}/media/
      - DASHBOARD_URL=http://${HOST_NAME}:9000/
      - ALLOWED_HOSTS=${HOST_NAME}
  storefront:
    build:
      context: ./saleor-storefront
      dockerfile: ./Dockerfile
      args:
        API_URI: https://${HOST_NAME}/graphql/
        GTM_ID: ${GTM_ID}
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /app/node_modules/
  dashboard:
    build:
      context: ./saleor-dashboard
      dockerfile: ./Dockerfile
      args:
        API_URI: http://${HOST_NAME}:8000/graphql/
    ports:
      - 9000:9000
    restart: always
    volumes:
      # - ./saleor-dashboard/:/app:cached
      - /app/node_modules/
    environment:
      - API_URI=http://${HOST_NAME}:8000/graphql/


  db:
    image: library/postgres:11.1-alpine
    restart: always
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: library/redis:5.0-alpine
    restart: always
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info
    restart: always
    networks:
      - saleor-backend-tier
    env_file: common.env
    depends_on:
      - redis
      - mailhog
    volumes:
      - ./saleor/saleor/:/app/saleor:Z,cached
      - ./saleor/templates/:/app/templates:Z,cached
      # shared volume between worker and api for media
      - saleor-media:/app/media
    environment:
      - EMAIL_URL=smtp://mailhog:1025

  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    networks:
      - saleor-backend-tier

  mailhog:
    image: mailhog/mailhog
    restart: always
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
